alias batch_1100='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch10DAC430_scope.yml config/asic_config_B18_slave_ch5DAC420.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1101='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch10DAC450_scope.yml config/asic_config_B18_slave_ch5DAC420.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1200='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch13DAC430_scope.yml config/asic_config_B18_slave_ch5DAC420.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1201='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch13DAC450_scope.yml config/asic_config_B18_slave_ch5DAC420.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'

alias ch_dac='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_oneCH.yml config/asic_config_B18_slave_allON.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'

alias batch_1300='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch0DAC420_scope.yml config/asic_config_B3_slave_ch5DAC460.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1301='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch0DAC440_scope.yml config/asic_config_B3_slave_ch5DAC460.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1400='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch1DAC390_scope.yml config/asic_config_B3_slave_ch1DAC540.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1401='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch1DAC410_scope.yml config/asic_config_B3_slave_ch1DAC540.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1500='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch2DAC400_scope.yml config/asic_config_B3_slave_ch2DAC430.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1501='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch2DAC420_scope.yml config/asic_config_B3_slave_ch2DAC430.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1600='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch12DAC430_scope.yml config/asic_config_B3_slave_ch12DAC470.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1601='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch12DAC450_scope.yml config/asic_config_B3_slave_ch12DAC470.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1700='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch11DAC440_scope.yml config/asic_config_B3_slave_ch10DAC450.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1701='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch11DAC460_scope.yml config/asic_config_B3_slave_ch10DAC450.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
