alias batch_1010='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch10DAC430_scope.yml config/asic_config_B18_slave_ch5DAC420.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1011='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch10DAC450_scope.yml config/asic_config_B18_slave_ch5DAC420.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1020='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch13DAC430_scope.yml config/asic_config_B18_slave_ch5DAC420.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1021='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch13DAC450_scope.yml config/asic_config_B18_slave_ch5DAC420.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'

alias ch_dac='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_oneCH.yml config/asic_config_B18_slave_allON.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'

alias batch_1030='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch0DAC420_scope.yml config/asic_config_B3_slave_ch5DAC460.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1031='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch0DAC440_scope.yml config/asic_config_B3_slave_ch5DAC460.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1040='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch1DAC390_scope.yml config/asic_config_B3_slave_ch1DAC540.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1041='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch1DAC410_scope.yml config/asic_config_B3_slave_ch1DAC540.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1050='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch2DAC400_scope.yml config/asic_config_B3_slave_ch2DAC430.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1051='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch2DAC420_scope.yml config/asic_config_B3_slave_ch2DAC430.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1060='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch12DAC430_scope.yml config/asic_config_B3_slave_ch12DAC470.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1061='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch12DAC450_scope.yml config/asic_config_B3_slave_ch12DAC470.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1070='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch11DAC440_scope.yml config/asic_config_B3_slave_ch10DAC450.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1071='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch11DAC460_scope.yml config/asic_config_B3_slave_ch10DAC450.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1080='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch3DAC380_scope.yml config/asic_config_B3_slave_ch3DAC510.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1081='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch3DAC400_scope.yml config/asic_config_B3_slave_ch3DAC510.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1090='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch5DAC530_scope.yml config/asic_config_B3_slave_ch5DAC460.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1091='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch5DAC550_scope.yml config/asic_config_B3_slave_ch5DAC460.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'

alias batch_1100='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch9DAC380_scope.yml config/asic_config_B3_slave_ch4DAC500.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
alias batch_1101='python scripts/DevGui.py --ip $fpga_ab $fpga_ad --userYaml config/asic_config_B13_master_ch9DAC400_scope.yml config/asic_config_B3_slave_ch4DAC500.yml --liveDisplay True --refClkSel ExtSmaClk ExtSmaClk'
