# Define the firmware version
export PRJ_VERSION = 0x00000001

# Define target output
target: prom

# Define target part
export PRJ_PART = XC7K70TFBG676-3

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
