Top:
  Fpga[:]: # "[:]" is a wildcard for a dict search
    ##########################################################################
    Asic: # Note: Configuration tuned for ASIC Board V1: #2
      ##########################################################################
      Trig:
        CalStrobeAlign: 0x3 # Cal pulse 40 Mhz alignment to 160 MHz
        EnCalPulseTrig: 0x1 # Enable Cal pulse to trigger readout      
        EnableReadout: 0x1
      ##########################################################################
      SlowControl:
        ########################
        EN_ck_SRAM[:]: 0x1
        ON_Ctest[:]: 0x0
        disable_pa[:]: 0x1
        bit_vth_cor[:]: 0x8
        ON_discri[:]: 0x0
        EN_hyst[:]: 0x1
        EN_trig_ext[:]: 0x0
        cBit_f_TOA[:]: 0x0        
        cBit_s_TOA[:]: 0x0
        cBit_f_TOT[:]: 0x0
        cBit_s_TOT[:]: 0x0
        cBit_c_TOT[:]: 0x0
        ########################
        EN_ck_SRAM[3]: 0x1
        ON_Ctest[3]: 0x1
        disable_pa[3]: 0x0
        bit_vth_cor[3]: 0x20
        ON_discri[3]: 0x1
        EN_hyst[3]: 0x1
        EN_trig_ext[3]: 0x0
        cBit_f_TOA[3]: 0x0 #0
        cBit_s_TOA[3]: 0x0 #0
        cBit_f_TOT[3]: 0xf #f
        cBit_s_TOT[3]: 0x0 #0
        cBit_c_TOT[3]: 0xf #f
        ########################      
        CP_b: 0x5 #5
        
        ext_Vcrtlf_en: 0x0 #0
        ext_Vcrtls_en: 0x1 #1
        ext_Vcrtlc_en: 0x0 #0

        totf_satovfw: 0x1
        totc_satovfw: 0x1
        toa_satovfw: 0x1      
      
        SatFVa: 0x3
        IntFVa: 0x1
        SatFTz: 0x4
        IntFTz: 0x1      
      
        cBitf: 0x0 #0
        cBits: 0xf #f
        cBitc: 0xf #f      
      
        Rin_Vpa: 0x1 #0
      
        cd[0]: 0x0 #6
        cd[1]: 0x0
        cd[2]: 0x0
        cd[3]: 0x0
        cd[4]: 0x0      
      
        dac_biaspa: 0x10 #10
      
        dac_pulser: 0x7 #7
        
        DAC10bit: 0x173 #173 / 183

      ##########################################################################
      Probe:
        en_probe_pa: 0x1
        en_probe_dig: 0x1 # pix=3
        pix[3]:
          probe_pa: 0x1
          probe_vthc: 0x0
          probe_dig_out_disc: 0x1
          probe_toa: 0x0
          probe_tot: 0x0
          totf: 0x0
          tot_overflow: 0x0
          toa_busy: 0x1
          tot_busy: 0x0
          tot_ready: 0x0
          en_read: 0x1
      ##########################################################################
      Readout:
        ReadoutSize: 0 # 0 pixel readout (zero inclusive)
        RdIndexLut[0]: 3 # pix=3
        OnlySendFirstHit: 0x1 # Only send the first hit per pixel
      ##########################################################################
